name: Uptdate README stats

on:
  workflow_dispatch:
    schedule:
      - cron: '0 * * * *'
jobs:  
 update-readme:
    name: Update stats Waka
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:

          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
          SHOW_TIME: true


          
